# -*- coding: utf-8 -*-
"""LEVEL 2 Mars dust phase: emit the EXACT bhmie Mie phase function P(theta) per
RGB as a GLSL const-array LUT (no 3-lobe HG fit, no texture binding). Same dust
model as _build/mars_dust_mie.py (feldspar+hematite, bimodal log-normal, Schneegans
et al. 2024). NO knee compression - the double-exp dust density tames the sunset.

Writes assets/mars_dust_phase_lut.glsl. When present, ShadowBuilder uses it as the
phase block instead of the embedded Level-1 HG fit (delete it to fall back to L1).
"""
import math, os
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "assets", "mars_dust_phase_lut.glsl")

HEMATITE = 1.0
LAMBDAS = [0.680, 0.550, 0.440]
M_RE = [1.52, 1.52, 1.52]
M_IM = [0.0008 * HEMATITE, 0.0100 * HEMATITE, 0.0400 * HEMATITE]
N_ANG = 361   # 0..180 deg, 0.5 deg steps


def bhmie(x, mre, mim, n_ang):
    y = complex(mre, mim) * x
    xstop = x + 4.0 * x ** (1.0 / 3.0) + 2.0
    nstop = int(xstop)
    nmx = int(max(xstop, abs(y)) + 15.0)
    D = np.zeros(nmx + 1, dtype=complex)
    for n in range(nmx, 0, -1):
        a = n / y
        D[n - 1] = a - 1.0 / (D[n] + a)
    amu = np.cos(np.linspace(0.0, math.pi, n_ang))
    pin0 = np.zeros(n_ang); pin1 = np.ones(n_ang)
    S1 = np.zeros(n_ang, dtype=complex); S2 = np.zeros(n_ang, dtype=complex)
    psi0, psi1 = math.cos(x), math.sin(x)
    chi0, chi1 = -math.sin(x), math.cos(x)
    xi1 = complex(psi1, -chi1); m = complex(mre, mim)
    qsca = qext = 0.0
    for n in range(1, nstop + 1):
        psi = (2.0 * n - 1.0) / x * psi1 - psi0
        chi = (2.0 * n - 1.0) / x * chi1 - chi0
        xi = complex(psi, -chi)
        ta = D[n] / m + n / x; tb = D[n] * m + n / x
        an = (ta * psi - psi1) / (ta * xi - xi1)
        bn = (tb * psi - psi1) / (tb * xi - xi1)
        tn = 2.0 * n + 1.0
        qsca += tn * (abs(an) ** 2 + abs(bn) ** 2)
        qext += tn * (an.real + bn.real)
        fn = tn / (n * (n + 1.0))
        tau = n * amu * pin1 - (n + 1.0) * pin0
        S1 += fn * (an * pin1 + bn * tau)
        S2 += fn * (an * tau + bn * pin1)
        pin0, pin1 = pin1, ((2.0 * n + 1.0) * amu * pin1 - (n + 1.0) * pin0) / n
        psi0, psi1 = psi1, psi
        chi0, chi1 = chi1, chi
        xi1 = complex(psi1, -chi1)
    inten = np.abs(S1) ** 2 + np.abs(S2) ** 2
    f = 2.0 / (x * x)
    return inten, qsca * f, qext * f


MODES = [
    dict(rg=0.04 * 1.1 ** -2.5, sig=math.sqrt(math.log(1.1)), w=1000.0),
    dict(rg=0.8 * 1.4 ** -2.5, sig=math.sqrt(math.log(1.4)), w=1.0),
]

def ndist(r):
    s = 0.0
    for m in MODES:
        lr = math.log(r / m["rg"])
        s += m["w"] / (r * m["sig"] * math.sqrt(2 * math.pi)) * math.exp(-lr * lr / (2 * m["sig"] ** 2))
    return s

NR, R_MIN, R_MAX = 120, 0.005, 5.0
radii = R_MIN * (R_MAX / R_MIN) ** (np.arange(NR) / (NR - 1))
wgt = np.zeros(NR)
for i in range(NR):
    dr = (radii[min(i + 1, NR - 1)] - radii[max(i - 1, 0)]) * 0.5
    wgt[i] = ndist(radii[i]) * dr

phase = np.zeros((3, N_ANG))
for c in range(3):
    lam = LAMBDAS[c]; k2 = (2 * math.pi / lam) ** 2
    agg = np.zeros(N_ANG); csca = 0.0
    for i in range(NR):
        if wgt[i] <= 0:
            continue
        inten, qs, qe = bhmie(2 * math.pi * radii[i] / lam, M_RE[c], M_IM[c], N_ANG)
        pir2 = math.pi * radii[i] ** 2
        csca += wgt[i] * qs * pir2
        agg += wgt[i] * inten / (2 * k2)
    phase[c] = agg / csca   # integrates to 1 over the sphere (same norm as HG)

print(f"forward peak P(0) R:G:B = {phase[:,0].round(2)}  back P(180) = {phase[:,-1].round(3)}")

entries = ",\n    ".join(
    f"vec3({phase[0][a]:.5g}, {phase[1][a]:.5g}, {phase[2][a]:.5g})" for a in range(N_ANG)
)
glsl = f"""// ---- Martian dust phase (LEVEL 2: exact bhmie Mie LUT, Schneegans et al. 2024) ----
// Exact per-angle P(theta) per RGB for feldspar+hematite dust (bimodal log-normal).
// NO knee compression - the double-exp dust density tames the sunset instead.
// {N_ANG} samples, 0..180 deg. Generated by make_mars_phase_lut.py - do not hand-edit.
#define MARS_DUST_LUT_N {N_ANG}
const vec3 MARS_DUST_PHASE_LUT[MARS_DUST_LUT_N] = vec3[MARS_DUST_LUT_N](
    {entries}
);

vec3 MarsDustPhaseFunction(float cosLight)
{{
    float theta = acos(clamp(cosLight, -1.0, 1.0));            // 0..PI
    float t = theta / PI * float(MARS_DUST_LUT_N - 1);
    int i = int(t);
    int j = min(i + 1, MARS_DUST_LUT_N - 1);
    return mix(MARS_DUST_PHASE_LUT[i], MARS_DUST_PHASE_LUT[j], t - float(i));
}}
// ---- end Martian dust phase ----

// Cornette-Shanks aproximation for mie phase function
// PATCHED (Level-2 Mie LUT): asymmetry.x < -0.5 selects the Martian dust phase LUT above.
vec3 MiePhaseFunction(float cosLight, vec3 asymmetry)
{{
    if (asymmetry.x < -0.5)
        return MarsDustPhaseFunction(cosLight);

    vec3 asymmetrySq = asymmetry * asymmetry;

    vec3 denom = 1.0 + asymmetrySq - 2.0 * asymmetry * cosLight;
    float numerator = 1.0 + cosLight * cosLight;

    return 1.5 / (4.0 * PI) * (1.0 - asymmetrySq) * pow(denom, vec3(-1.5)) * numerator / (2.0 + asymmetrySq);
}}
"""
open(OUT, "w").write(glsl)
print("wrote", OUT, f"({N_ANG} samples)")
