// ---- Martian dust phase function (Mie theory, Schneegans et al. 2024) ----
// 3-lobe HG fit per RGB channel of bhmie output for feldspar+hematite dust
// (bimodal log-normal sizes). Generated by _build/mars_dust_mie.py - do not hand-edit.
vec3 MarsDustHG(float g_scale, vec3 g, float cosLight)
{
    vec3 gg = g * g;
    return (vec3(1.0) - gg) / (4.0 * PI * pow(vec3(1.0) + gg - 2.0 * g * cosLight, vec3(1.5))) * g_scale;
}

// Soft radiance compression of the forward spike: KSA has no exposure control, so
// the physically-correct peak (P~10/sr near 0 deg) washes the sunset out. This is
// "exposure applied in the medium": identity for P << MARS_DUST_PHASE_KNEE, smooth
// compression above it. Only the innermost few degrees around the sun are affected.
#define MARS_DUST_PHASE_KNEE 8.0

vec3 MarsDustPhaseFunction(float cosLight)
{
    vec3 p = vec3(0.0);
    p += vec3(0.1726, 0.4362, 0.6934) * MarsDustHG(1.0, vec3(0.9050, 0.8900, 0.9000), cosLight);
    p += vec3(0.7728, 0.5176, 0.2683) * MarsDustHG(1.0, vec3(0.7100, 0.6500, 0.5000), cosLight);
    p += vec3(0.0546, 0.0462, 0.0384) * MarsDustHG(1.0, vec3(-0.5000, -0.5000, -0.5000), cosLight);
    return p / (vec3(1.0) + p / MARS_DUST_PHASE_KNEE);
}
// ---- end Martian dust phase function ----
